# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=63)),
                ('description', models.CharField(blank=True, db_index=True, max_length=63)),
                ('type', models.IntegerField(db_index=True, editable=False)),
                ('inactive_pledges', models.IntegerField(db_index=True, default=0)),
                ('active_pledges', models.IntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
