# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='impact',
            field=models.CharField(blank=True, db_index=True, max_length=63),
        ),
    ]
