# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deeds', '0002_deed_impact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_threshold', models.IntegerField(db_index=True, default=0)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='deed',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deed',
            name='impact',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deed',
            name='title',
            field=models.CharField(db_index=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='deed',
            name='type',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pledge',
            name='deed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deeds.Deed'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
