# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0003_auto_20161027_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
