# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0004_auto_20161103_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='pledge_threshold',
            new_name='threshold',
        ),
    ]
